"""added email column in user

Revision ID: 290956bd09ca
Revises: d16bc57290d6
Create Date: 2025-07-29 18:03:01.176150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290956bd09ca'
down_revision = 'd16bc57290d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
