"""Add chosen_option and correct_option to QuestionStatus

Revision ID: d16bc57290d6
Revises: 
Create Date: 2025-07-29 02:49:29.200132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16bc57290d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chosen_option', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_option', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_status', schema=None) as batch_op:
        batch_op.drop_column('correct_option')
        batch_op.drop_column('chosen_option')

    # ### end Alembic commands ###
